export const chatTypes = {
  LOAD_USERS: 'LOAD_USERS',
  CLEAN_CHAT: 'CLEAN_CHAT',
  ADD_MESSAGE: 'ADD_MESSAGE',
  LOAD_MESSAGES: 'LOAD_MESSAGES',
  SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',
  PURGE_CHAT_STATE: 'PURGE_CHAT_STATE'
}
